### ISSUE TITLE
access to the attachments/payload of mails

### ISSUE THREAD

**Issue by ckluss** [allanvc/mRpostman#1]
Hi Allan

thank you for this excellent library. 

Will it be possible to get access to the attachments/payload of the mails in future releases?

Kind regards
Christof

**Comment by allanvc** [comment]
Hi Christof,

Thank you!

That feature is definitely in our plans.

A colleague and I are already studying how to decode the attachment received as base64 text, and save it with the appropriate file extension. Maybe we will have a `get_attachment()` function or something like that in the next couple of months.

Best regards,

Allan

**Comment by allanvc** [comment]
Hi Christof,

I've just updated the repo to version 0.3.0, which includes support for listing and getting attachments encoded as base64 text.
Please, take a look at [mRpostman basics Vignette - Item 7](https://allanvc.github.io/mRpostman/articles/basics.html#attachments).

Could you please test it and see if it works for you?

I tested it with GMail, AOL, Yahoo and Yandex, with messages exchanged between them, and also with messages sent to these servers from an Outlook/Exchange server. It worked as expected.

Sometimes, it is necessary to increase the `timeout_ms` parameter inside `configure_imap()`, e.g. `timeout_ms = 60000`, so you don't get a connection timeout error when fetching full messages that contain large attachments.

Best,

Allan
