### ISSUE TITLE
Downloaded attached *.csv Files seem strange

### ISSUE THREAD

**Issue by methodenzentrum** [allanvc/mRpostman#11]
I downloaded a attached *.csv File with fetch_attachments().  
It is saved with correct filename and *.csv extension. 
If i open it from folder it looks like this:

 ÔD@Îd€d@3™TäM Á9“@s@0@ÎdÀæKTS-R„4Õ
xœ†Õ^­©ì´ÚËTÐ«w;Rgëj­Š×¥-Q‘PóÄ•ç«Áéçž'!¶·¥zö§µ2ÍdËjëhìÚzmy•°HCD Ö@´À5‘LBßjYli¼‰È^ÛL³Y rÃ5-Q
I^·;^UêÚžËmz¹¢%’$Ò
DBU
 LµR=BD0„Ó‚Ô4j!eè¥z{¦n»œÐ1Þ®³Ú¶¸œ§ß• ....

Any Ideas?

**Comment by allanvc** [comment]
Hi.
Sorry, for my long delay.
Unfortunately, I don`t know how to help you in this case. I have not figured out a completely fail-proof way of converting the binary files into the proper extensions. Sometimes, that kind of problem may happen. Sorry again.
If you managed to solve this problem, please let me know.
Allan
