### ISSUE TITLE
Outlook email: Authentication failed

### ISSUE THREAD

**Issue by jayantam** [allanvc/mRpostman#14]
I am trying to connect to my office email server, Microsoft Office365. I am using the following code:

library(mRpostman)
# Outlook - Office 365
con <- configure_imap(url="imaps://outlook.office365.com",
                  username="your_user@company.com",
                  password="outlook_password")

con$list_server_capabilities()

I am getting the following error:
Error in response_error_handling(e$message[1]) : 
  Login denied: the server returned an authentication error.

I am sure I am using correct username & password which is working fine in my outlook client.

Please let me know if anything else to be done to get connected to Office365 outlook email server to read the emails.

Thanks.

**Comment by allanvc** [comment]
Hi. 
Is it possible that "your_user" is an alias to the original email account? For example, one of my Office365 email accounts is "allan.quadros@company.com". However, this is just an alias to "325433@company.com". If this is the case, then you should pass "325433@company.com" as the username.

**Comment by jayantam** [comment]
No, there is no alias user name to my email account. Still I have checked it in my outlook client account setting.

Is it related to recent policy change from MS office365 where any third party application can not be authenticated using the username/password used in MS outlook client? I think similar policy for gmail account also where we have to use 2FA password for connecting to gmail account using any third party application.

**Comment by allanvc** [comment]
That might be the case, and you will probably be able to authenticate using OAuth2.
Please, take a look at this website: 
- https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth

And also this vignette:
- https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth

Please, let me know if that works.
Thanks,
Allan
