### ISSUE TITLE
Can't get fetch_attachments working when filename is not in Content-Disposition

### ISSUE THREAD

**Issue by StevenLarsen89** [allanvc/mRpostman#5]
Hi,

I am trying to fetch attachments from several e-mails but there is one e-mail, where I cannot get fetch_attachments to work. I have been digging around and it seems like the issue is, that there is no filename in the Content-Disposition:

```
----boundary_0_64335382-9e7b-474a-86f6-1f8e8487526c
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: base64

----boundary_0_64335382-9e7b-474a-86f6-1f8e8487526c
Content-Type: application/octet-stream; name=filename.csv
Content-Transfer-Encoding: base64
Content-Disposition: attachment
```
Is there a workaround?

Kind regards,
Steven

**Comment by allanvc** [comment]
Hi, thanks!

As a quick workaround, I would suggest the `fetch_body()` + `get_attachments()` combo:

```
your_msg_id %>%
 con$fetch_body() %>%
 con$get_attachments()
```
It is not guaranteed, but I would try that first.
 
Also, if possible, please forward that same e-mail to quadros@ksu.edu or allanvcq@gmail.com. Perhaps, it will be necessary to upload a bug fix. This would help me with the tests.

Best,

Allan

**Comment by StevenLarsen89** [comment]
Hi Allan,

The following sadly didn't do the job. 
> ```
> your_msg_id %>%
>  con$fetch_body() %>%
>  con$get_attachments()
> ```

I did some more testing and discovered that when I forwarded the e-mail, then the `filename` appeared in the `Content-Disposition`. This means that it makes no sense forwarding to you either since the challenge dissapears.  It did however solve my problem. It is a bit of a hack, but I have made a rule in outlook, so that the specific e-mail is always forwarded to myself. Then I can fetch the attachment.

The e-mail in question is sent by an external supplier, so maybe the "error" occurs because of the way their e-mail system constructs the e-mail. Not sure. Anyways, thanks for the fast reply. It led me in the right direction.

Regards,
Steven

**Comment by allanvc** [comment]
Hi Steven,

Sorry for the late answer.
I am glad you've found a way of getting things working.
I will try to investigate and replicate this issue in order to come up with a solution for these cases. Unfortunately, this occurs because there are a bunch of servers that do not respect the RFCs commandments, and it causes a lot of headaches...

Thanks,

Allan
