### ISSUE TITLE
Problem with iRedMail email server

### ISSUE THREAD

**Issue by dennishwuh** [allanvc/mRpostman#6]
Hi allanvc,

I use iRedMail as company mail server with self-signed certificate.
`con <- configure_imap(
  url="imap://my_server_ip",
  username="username@mywebsite.com", 
  password="myaccountPassword", 
  verbose = T,
  login_options = "AUTH=PLAIN"
)`

TCP_NODELAY is set successfully and connected to my_server_ip on port 143

But another error is:
`* SSL certificate problem: self signed certificate`

Is there any option that I can disable SSL check.
Could you please help me, thanks for your time.

**Comment by allanvc** [comment]
Hi,

Please, try `use_ssl = FALSE` in `configure_imap()`. However, note that this workaround is dangerous.
I also recommend that you take a look at libcurl's documentation on [SSL certificates](https://curl.se/docs/sslcerts.html).

**Comment by dennishwuh** [comment]
I worked around and it's works fine atm:
1. Enable less secure IMAP/POP3 without STARTTLS https://ixnfo.com/en/allow-insecure-connections-to-pop3-imap-iredmail.html
```
sudo nano /etc/dovecot/dovecot.conf
disable_plaintext_auth=no
ssl=yes
```
2. Init the connection as below:
```
con <- configure_imap(
  url="imap://my_server_ip",
  username="username@my_domain",
  password="password_here",
  use_ssl = F, 
  verbose = T,
  login_options = "AUTH=PLAIN"
)
```
