### ISSUE TITLE
Search_on error

### ISSUE THREAD

**Issue by StevenLarsen89** [allanvc/mRpostman#7]
Hi,

Ever since the May 1. I have been getting this error:

> execute_search(self = self, url = url, handle = h, customrequest = customrequest,  : 
>  Request error: the server returned an error.

when using the search_on() function. Did some functionality change? I have not been able to figure out what is going on.

Regards,
Steven

**Comment by allanvc** [comment]
Hi Steven,

It seems to me that your IMAP provider stopped the support for the `SEARCH ON` IMAP functionality. That also happened with one of my accounts last year. I can't recall now if it was on Yahoo or Gmail. mRpostman had no updates on the days before May 1st, which reinforces that hypothesis. You can use the `search_period` or even `search_since` methods as alternatives to `search_on()`. You only have to switch the dates around. Would you mind if I ask what is your IMAP provider?

Thanks,
Allan
