### ISSUE TITLE
TLS issue ? 

### ISSUE THREAD

**Issue by neonira** [allanvc/mRpostman#9]
Using very simple following mRpostman approach to get access to one of my imap accounts, I got  error described here after

<pre>
require(mRpostman)
con <- configure_imap(
  url="imaps://imap....:143",
  username="marketing@....com",
  password='8Z...',
  verbose=TRUE,
  use_ssl = TRUE
)
con$list_server_capabilities()
</pre>

<pre style='color:orange'>
* Hostname XXXXXXXX was found in DNS cache
*   Trying ...
* TCP_NODELAY set
* Connected to .... port 143 
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 
Error in list_server_capabilities_int(self, retries) : 
  Request error: the server returned an error.
</pre>

Any idea about how to solve the issue?
My guess is that I need to use start_tls option with accept_all security level, as this server provides an own signed certificate.

**Comment by allanvc** [comment]
Sorry for my delay! I have been really busy in the last few months. Unfortunately, I haven’t seen their error before myself. Please take a look at this StackOverflow question [https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number](https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number). If you have already found a solution, please let me know.
Thanks,
Allan
